
main: src/main.c src/circle.c src/colors.c src/complex.c src/descartes.c
	mkdir -p build/
	gcc -Wall -Wextra -I./include -o build/main src/main.c src/circle.c src/colors.c src/complex.c src/descartes.c -L./lib/ -lraylib -lm
